name: rustic
description: Various constructs inspired by the Rust programming language.
version: 0.1.0
repository: https://github.com/skreborn/rustic

environment:
  sdk: '>=2.9.0 <3.0.0'

dependencies:
  equatable: ^1.0.0
  meta: ^1.2.0

dev_dependencies:
  benchmark_harness: ^1.0.0
  test: ^1.15.0
