name: rustic
description: Various constructs inspired by the Rust programming language.
version: 0.3.0
repository: https://github.com/skreborn/rustic

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  equatable: ^2.0.0
  meta: ^1.0.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  test: ^1.0.0
