name: rustic
description: Various constructs inspired by the Rust programming language.
version: 0.5.1
repository: https://github.com/skreborn/rustic

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  meta: ^1.4.0

dev_dependencies:
  benchmark_harness: ^2.0.0
  checks: ^0.2.0
  lints: ^2.0.0
  test: ^1.0.0
